version: '3.8'

services:
  web:
    build: .
    ports:
      - "4500:80"
    links:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: @Teste2023
      MYSQL_DATABASE: mydatabasetest

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8080:80"
    links:
      - db